# Generated by Django 3.2.9 on 2021-11-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='app_id',
            new_name='appId',
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
